### ISSUE TITLE
Support pages which has single quote / apostrophes in title

### ISSUE THREAD

**Issue by gautamborad** [aaronbieber/org-protocol-handler#1]
Thanks for this applescript, its working great!! However, it errors out where the page title has a single quote. You can try it on: http://terrytangyuan.github.io/2016/03/14/scikit-flow-intro/

This is a problem since `encodeURIComponent` does not escape single quotes. The same case will be applicable to apostrophes also.

One more thing `display notification "Saved \"" & pageTitle & "\""` get triggered even after the "on error" block. For now, i have added a return just before the `end try`.

**Comment by aaronbieber** [comment]
I am looking into this right now, thanks for the report.

**Comment by aaronbieber** [comment]
It looks like the problem isn't with the URL encoding, but rather with the shell escaping when sending that string on to the `emacsclient` command. Emacs doesn't want to receive a URL-encoded value at all, it would rather receive a plaintext URL, but because this URL has both spaces and single quotes in it, the command just fails.

I've added `quoted form of` to the value in the `do shell script` line and that seems to fix it, I'll push that patch in a minute.
